global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "bun-server"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # use localhost:3000 if Prometheus runs locally
